//! Public atom view — the wire-visible subset of a memory atom.
//!
//! This type contains only the fields that agents and users can see.
//! Internal fields (certainty scores, ranking signals, canonical markers,
//! topic keys) are intentionally excluded.

/// A memory atom as seen by agents and users over the wire.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct AtomView {
    /// ULID — globally unique, embeds creation timestamp.
    pub id: String,

    /// The raw content text.
    pub content: String,

    /// Optional structured content (JSON).
    pub structured: Option<serde_json::Value>,

    /// When this memory was created (ISO 8601).
    pub created_at: String,

    /// When this memory was last modified (ISO 8601).
    pub updated_at: Option<String>,

    /// Current assertion polarity.
    pub polarity: Polarity,

    /// Current epistemic status.
    pub epistemic: EpistemicStatus,

    /// Current governance exposure state.
    pub exposure: ExposureState,

    /// Sensory modality.
    pub modality: Modality,

    /// Optional category coordinate.
    pub category: Option<String>,

    /// Provenance — where this memory came from.
    pub source: Option<String>,

    /// Modality of the source (user, agent, system, observation).
    pub source_modality: Option<String>,
}

/// Assertion polarity — whether the memory is asserted as true, false, or
/// conditionally true.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Polarity {
    /// The memory is asserted as true.
    Positive,
    /// The memory has been negated (corrected to false).
    Negative { reason: Option<String> },
    /// The memory is true only under certain conditions.
    Conditional { condition: Option<String> },
}

/// Epistemic status — the degree of belief in the memory.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum EpistemicStatus {
    /// Possibly true (unverified).
    Possible,
    /// Confirmed as actually true.
    Actual,
    /// Necessarily true (axiomatic within the system).
    Necessary,
}

/// Governance exposure state — who can see this memory.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ExposureState {
    /// Visible in normal recall.
    Visible,
    /// Restricted; not visible in normal recall but accessible in governance views.
    Quarantined,
    /// Permanently sealed; no further modifications allowed.
    Sealed,
    /// Tombstoned; content replaced with a marker.
    Tombstoned,
    /// A derived lesson from a governed atom.
    Lesson,
}

/// Sensory modality — how the memory entered the system.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Modality {
    /// Direct text input.
    Text,
    /// Structured code (source, config, schema).
    Code,
    /// Observed event or pattern.
    Observation,
    /// Generated by the system.
    System,
    /// Extracted from dialogue.
    Dialogue,
    /// Multi-modal content (image, audio, etc.).
    MultiModal,
}
