name: Commit Lint on Approval

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  approval-commitlint:
    name: approval-commitlint
    if: github.event.review.state == 'approved'
    uses: HMG-AI/.github/.github/workflows/reusable-commitlint.yml@593e8e253dd3ca85dace3ebe24383d2a131592d5
    with:
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}

