name: Commit Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

concurrency:
  group: commitlint-${{ github.event.pull_request.number || github.event.merge_group.head_sha }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: commitlint
    uses: HMG-AI/.github/.github/workflows/reusable-commitlint.yml@978d6d08d6bfc1e8a3662c1f9b0daab8bfa0e557
    with:
      base_sha: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha }}
      head_sha: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
